var tagible = function() {
  this.placeList = [
    {
      text: '',
      geo: {
        lat: 12.0,
        lon: 33.5
      }
    },
  ];
  this.walkTheDOM = function (node, func) {
    func(node);
    node = node.firstChild;
    while (node) {
        this.walkTheDOM(node, func);
        node = node.nextSibling;
    }
  }

  this.processContainer = function(container) {
    var actualContainer = {};
    if(container.length < 1) {
      console.log('Invalid Container Query');
      return 
    }
    // Yes this is an assumption that there could be more as we are only passing in DOM by className query
    actualContainer = container[0];
    console.log(actualContainer.textContent);
    this.walkTheDOM(actualContainer, function (node) {
      if (node.nodeType === 3) { // Is it a Text node?
          var text = node.data.trim();
          if (text.length > 0) { // Does it have non white-space text content?
              //console.log(text);
          }
      }
    });
  }


  this.apiData = {
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "url": "",
    "totalTransactions": "2",
    "language": "english",
    "entities": [
      {
        "type": "PrintMedia",
        "relevance": "0.879993",
        "sentiment": {
          "type": "positive",
          "score": "0.143276",
          "mixed": "1"
        },
        "count": "4",
        "text": "Gothic Quarter"
      },
      {
        "type": "Facility",
        "relevance": "0.825839",
        "sentiment": {
          "type": "positive",
          "score": "0.469708"
        },
        "count": "1",
        "text": "Gothic Centre of Barcelona"
      },
      {
        "type": "City",
        "relevance": "0.754509",
        "sentiment": {
          "type": "positive",
          "score": "0.671345"
        },
        "count": "3",
        "text": "Barcelona",
        "disambiguated": {
          "subType": [
            "Country",
            "OlympicHostCity"
          ],
          "name": "Barcelona",
          "geo": "41.38333333333333 2.183333333333333",
          "website": "http://www.bcn.cat/english/ihome.htm",
          "dbpedia": "http://dbpedia.org/resource/Barcelona",
          "freebase": "http://rdf.freebase.com/ns/m.01f62",
          "geonames": "http://sws.geonames.org/3128760/",
          "yago": "http://yago-knowledge.org/resource/Barcelona"
        }
      },
      {
        "type": "Facility",
        "relevance": "0.663913",
        "sentiment": {
          "type": "positive",
          "score": "0.531958"
        },
        "count": "1",
        "text": "Barcelona Cathedral",
        "disambiguated": {
          "name": "Barcelona Cathedral",
          "dbpedia": "http://dbpedia.org/resource/Barcelona_Cathedral",
          "freebase": "http://rdf.freebase.com/ns/m.0vlyb"
        }
      },
      {
        "type": "Facility",
        "relevance": "0.577851",
        "sentiment": {
          "type": "negative",
          "score": "-0.217952"
        },
        "count": "1",
        "text": "Gothic Palaces"
      },
      {
        "type": "Facility",
        "relevance": "0.544865",
        "sentiment": {
          "type": "positive",
          "score": "0.348783"
        },
        "count": "1",
        "text": "Cathedral de la Santa Cruz"
      },
      {
        "type": "City",
        "relevance": "0.348704",
        "sentiment": {
          "type": "neutral"
        },
        "count": "1",
        "text": "La Boquieria"
      },
      {
        "type": "Facility",
        "relevance": "0.338834",
        "sentiment": {
          "type": "neutral"
        },
        "count": "1",
        "text": "Ronda de Sant Pere"
      },
      {
        "type": "Facility",
        "relevance": "0.307387",
        "sentiment": {
          "type": "neutral"
        },
        "count": "1",
        "text": "Old Town",
        "disambiguated": {
          "name": "Thomas Brown House (Franklin, Tennessee)",
          "dbpedia": "http://dbpedia.org/resource/Thomas_Brown_House_(Franklin,_Tennessee)",
          "freebase": "http://rdf.freebase.com/ns/m.0fq14fh"
        }
      },
      {
        "type": "Facility",
        "relevance": "0.286749",
        "sentiment": {
          "type": "positive",
          "score": "0.719126"
        },
        "count": "1",
        "text": "Las Ramblas"
      },
      {
        "type": "Person",
        "relevance": "0.280417",
        "sentiment": {
          "type": "neutral"
        },
        "count": "1",
        "text": "Barri Gòtic"
      },
      {
        "type": "Person",
        "relevance": "0.259001",
        "sentiment": {
          "type": "positive",
          "score": "0.272339"
        },
        "count": "1",
        "text": "Marvel"
      },
      {
        "type": "Quantity",
        "relevance": "0.259001",
        "sentiment": {
          "type": "neutral"
        },
        "count": "1",
        "text": "three-hour"
      }
    ]
  };
};

var t = new tagible();
console.log(t);
t.processContainer(document.getElementsByClassName('whatsincluded'));